#pragma once
#include <QCoreApplication>
#include <QHash>
#include <QString>
#include <QVariant>
#include <QRegularExpression>
#include <algorithm>
namespace VaporView::Map3D {
inline const QHash<QString, QString>& mapLanguageCatalog() {
    static const QHash<QString, QString> catalog{
        {QStringLiteral("高度基准仅用于显示；不用于离地高度或地形净空判断"), QStringLiteral("vertical reference applied for display; no AGL/terrain-clearance decision")},
        {QStringLiteral("WGS84 椭球高"), QStringLiteral("WGS84 ellipsoid")},
        {QStringLiteral("本地 NED"), QStringLiteral("local NED")},
        {QStringLiteral("未知"), QStringLiteral("unknown")},
        {QStringLiteral("固定解"), QStringLiteral("Fixed")},
        {QStringLiteral("浮点解"), QStringLiteral("Float")},
        {QStringLiteral("单点定位"), QStringLiteral("Single")},
        {QStringLiteral("无效"), QStringLiteral("Invalid")},
        {QStringLiteral("无"), QStringLiteral("none")},
        {QStringLiteral("四元数"), QStringLiteral("Quaternion")},
        {QStringLiteral("欧拉角"), QStringLiteral("Euler")},
        {QStringLiteral("可用"), QStringLiteral("available")},
        {QStringLiteral("缺失"), QStringLiteral("missing")},
        {QStringLiteral("未选择（%1/4 个文件）"), QStringLiteral("not selected (%1/4 files)")},
        {QStringLiteral("%1 个安全图层（水系/道路，%2/4 个文件）"), QStringLiteral("%1 safe layers (water/roads, %2/4 files)")},
        {QStringLiteral("缺少 VRT 或模板"), QStringLiteral("missing VRT/template")},
        {QStringLiteral("已选点 #%1"), QStringLiteral("Selected #%1")},
        {QStringLiteral("纬度 %1"), QStringLiteral("Lat %1")},
        {QStringLiteral("经度 %1"), QStringLiteral("Lon %1")},
        {QStringLiteral("高度 %1 m %2"), QStringLiteral("H %1 m %2")},
        {QStringLiteral("定位 %1"), QStringLiteral("Fix %1")},
        {QStringLiteral("卫星数 %1"), QStringLiteral("Sats %1")},
        {QStringLiteral("记录时间 %1"), QStringLiteral("rec %1")},
        {QStringLiteral("设备时间 %1"), QStringLiteral("dev %1")},
        {QStringLiteral("姿态 %1"), QStringLiteral("Att %1")},
        {QStringLiteral("已使用轻量 Natural Earth 底图快速打开三维地图；选择“重载最佳本地地图”加载 DEM、OSM 和三维建筑资源。"), QStringLiteral("Started with lightweight Natural Earth; use Reload best local map to load DEM, OSM and 3D buildings.")},
        {QStringLiteral("打开三维地图时不会自动加载大型本地地图资源。"), QStringLiteral("Heavy local map resources are not auto-loaded when the 3D Map window opens.")},
        {QStringLiteral("Natural Earth 底图及可用的本地 DEM 地形。"), QStringLiteral("Natural Earth with available local DEM terrain.")},
        {QStringLiteral("固定解 %1 浮点解 %2 差分 %3 单点 %4 未知 %5 无效 %6 跳变 %7"), QStringLiteral("Fixed %1 Float %2 DGPS %3 Single %4 Unknown %5 Invalid %6 Jump %7")},
        {QStringLiteral("未加载"), QStringLiteral("unloaded")},
        {QStringLiteral("播放中"), QStringLiteral("playing")},
        {QStringLiteral("已停止"), QStringLiteral("stopped")},
        {QStringLiteral("已暂停"), QStringLiteral("paused")},
        {QStringLiteral("VaporView 三维地图"), QStringLiteral("VaporView 3D Map")},
        {QStringLiteral("糖果色"), QStringLiteral("Candy")},
        {QStringLiteral("蓝红渐变"), QStringLiteral("BlueRedFast")},
        {QStringLiteral("反向光谱"), QStringLiteral("SpectralReverse")},
        {QStringLiteral("无渲染测试模式；未尝试加载地图场景。"), QStringLiteral("Headless test mode; earth loading was not attempted.")},
        {QStringLiteral("尚未启动三维渲染。"), QStringLiteral("3D rendering has not been started.")},
        {QStringLiteral("实时"), QStringLiteral("Live")},
        {QStringLiteral("实时数据批次为空"), QStringLiteral("empty live batch")},
        {QStringLiteral("轨迹已清空"), QStringLiteral("track cleared")},
        {QStringLiteral("已排队等待加载最新会话轨迹…"), QStringLiteral("Queued latest session track request...")},
        {QStringLiteral("正在加载会话 轨迹及热力数据，完成后自动定位…"), QStringLiteral("Loading session track and heat data; view will focus when ready...")},
        {QStringLiteral("会话轨迹"), QStringLiteral("Session Track")},
        {QStringLiteral("会话"), QStringLiteral("Session")},
        {QStringLiteral("自动轨迹视角"), QStringLiteral("Track auto")},
        {QStringLiteral("已从 %2 加载 %1 个采样点%3%4"), QStringLiteral("Loaded %1 samples from %2%3%4")},
        {QStringLiteral("界面测试模式；未尝试加载外部地图场景。"), QStringLiteral("UI test mode; external earth/map loading was not attempted.")},
        {QStringLiteral("所选地图场景文件不存在。"), QStringLiteral("Selected earth file does not exist.")},
        {QStringLiteral("用户选择的自定义地图场景。"), QStringLiteral("User-selected custom Earth scene.")},
        {QStringLiteral("使用用户选择的自定义地图场景文件。"), QStringLiteral("Using user-selected custom earth file.")},
        {QStringLiteral("osgEarth 场景 (*.earth);;所有文件 (*)"), QStringLiteral("osgEarth (*.earth);;All Files (*)")},
        {QStringLiteral("已加载用户选择的地图场景文件。"), QStringLiteral("Loaded user-selected earth file.")},
        {QStringLiteral("已加载地图场景：%1%2"), QStringLiteral("Loaded earth file: %1%2")},
        {QStringLiteral("Natural Earth 底图叠加 %1。"), QStringLiteral("Natural Earth background with %1 overlay.")},
        {QStringLiteral("已加载可选本地影像模板：%1"), QStringLiteral("Loaded optional local imagery template: %1")},
        {QStringLiteral("缩放后自动加载本地影像模板：%1"), QStringLiteral("Automatically loaded local imagery template after zoom: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片不符合格式约定；请打开地图诊断查看详情。"), QStringLiteral("Native OSG building tiles contract is not valid; open Map Data Diagnostics for details.")},
        {QStringLiteral("已清除本地 OSG 建筑叠加层。"), QStringLiteral("Local OSG building overlay cleared.")},
        {QStringLiteral("飞行器"), QStringLiteral("Aircraft")},
        {QStringLiteral("飞行器不可用"), QStringLiteral("Aircraft unavailable")},
        {QStringLiteral("轨迹"), QStringLiteral("Track")},
        {QStringLiteral("轨迹不可用"), QStringLiteral("Track unavailable")},
        {QStringLiteral("重置"), QStringLiteral("Reset")},
        {QStringLiteral("三维地图数据诊断"), QStringLiteral("3D Map Diagnostics")},
        {QStringLiteral("回放"), QStringLiteral("Replay")},
        {QStringLiteral("采样点：%1/%2"), QStringLiteral("Points: %1/%2")},
        {QStringLiteral("正在加载会话（完成后自动定位） | "), QStringLiteral("Loading session (auto focus when ready) | ")},
        {QStringLiteral(" | 质量 %1"), QStringLiteral(" | Q %1")},
        {QStringLiteral(" | 热力 %1"), QStringLiteral(" | Heat %1")},
        {QStringLiteral(" | 来源 %1"), QStringLiteral(" | Source %1")},
        {QStringLiteral(" | 视角 %1"), QStringLiteral(" | Camera %1")},
        {QStringLiteral(" | 跟随 %1"), QStringLiteral(" | Follow %1")},
        {QStringLiteral("开启"), QStringLiteral("on")},
        {QStringLiteral("关闭"), QStringLiteral("Close")},
        {QStringLiteral(" 记录时间 %1"), QStringLiteral(" rec %1")},
        {QStringLiteral(" 设备时间 %1"), QStringLiteral(" dev %1")},
        {QStringLiteral(" | 最近丢弃 %1：%2"), QStringLiteral(" | Last drop %1: %2")},
        {QStringLiteral(" | 地图 %1 | 视口 %2×%3"), QStringLiteral(" | Map %1 | View %2x%3")},
        {QStringLiteral(" | 影像 天地图卫星"), QStringLiteral(" | Imagery Tianditu satellite")},
        {QStringLiteral(" | 分段 %1×%2 | FPS %3 | CPU %4 ms | 轨迹 %5 ms"), QStringLiteral(" | Seg %1x%2 | FPS %3 | CPU %4 ms | Track %5 ms")},
        {QStringLiteral(" | 纬度 %1 经度 %2 高度 %3 m %4 | 定位 %5 | 卫星数 %6 | HDOP %7"), QStringLiteral(" | Lat %1 Lon %2 H %3 m %4 | Fix %5 | Sats %6 | HDOP %7")},
        {QStringLiteral(" | 已应用高度基准"), QStringLiteral(" | Height ref applied")},
        {QStringLiteral(" | 高度基准假定为 WGS84"), QStringLiteral(" | Height ref assumed WGS84")},
        {QStringLiteral(" | 高度基准优先使用记录的 ECEF"), QStringLiteral(" | Height ref uses recorded ECEF when available")},
        {QStringLiteral(" | 姿态 %1"), QStringLiteral(" | Att %1")},
        {QStringLiteral(" | 选中 #%1"), QStringLiteral(" | Selected #%1")},
        {QStringLiteral(" 纬度 %1 经度 %2 高度 %3 m | 定位 %4"), QStringLiteral(" Lat %1 Lon %2 H %3 m | Fix %4")},
        {QStringLiteral("Sentinel-2 本地影像"), QStringLiteral("Sentinel-2 local imagery")},
        {QStringLiteral("Landsat 本地影像"), QStringLiteral("Landsat local imagery")},
        {QStringLiteral("OpenAerialMap 本地影像"), QStringLiteral("OpenAerialMap local imagery")},
        {QStringLiteral("原生 OSG 建筑瓦片集超过 64 MiB 安全上限。"), QStringLiteral("Native OSG building tileset exceeds the 64 MiB safety limit.")},
        {QStringLiteral("无法打开原生 OSG 建筑瓦片集：%1"), QStringLiteral("Native OSG building tileset could not be opened: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片集不是有效 JSON：%1"), QStringLiteral("Native OSG building tileset is not valid JSON: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片集缺少 asset 对象。"), QStringLiteral("Native OSG building tileset is missing asset object.")},
        {QStringLiteral("原生 OSG 建筑瓦片集缺少 asset.version。"), QStringLiteral("Native OSG building tileset asset.version is missing.")},
        {QStringLiteral("本地建筑瓦片集 extras.format 必须为 vaporview-osg-native-building-tiles；此加载器不支持通用 Cesium 3D Tiles 数据块。"), QStringLiteral("Local building tileset extras.format must be vaporview-osg-native-building-tiles; generic Cesium 3D Tiles payloads are not supported by this loader.")},
        {QStringLiteral("原生 OSG 建筑瓦片集缺少根瓦片。"), QStringLiteral("Native OSG building tileset is missing root tile.")},
        {QStringLiteral("原生 OSG 建筑根瓦片缺少 boundingVolume。"), QStringLiteral("Native OSG building tileset root tile is missing boundingVolume.")},
        {QStringLiteral("原生 OSG 建筑瓦片集或根瓦片缺少 geometricError。"), QStringLiteral("Native OSG building tileset/root geometricError is missing.")},
        {QStringLiteral("原生 OSG 建筑瓦片集超过遍历安全上限。"), QStringLiteral("Native OSG building tileset exceeds the traversal safety limit.")},
        {QStringLiteral("原生 OSG 建筑瓦片集没有 content.uri 条目。"), QStringLiteral("Native OSG building tileset has no content.uri entries yet.")},
        {QStringLiteral("原生 OSG 建筑瓦片集包含空资源 URI。"), QStringLiteral("Native OSG building tileset contains an empty content URI.")},
        {QStringLiteral("原生 OSG 建筑瓦片资源 URI 不是可移植本地路径：%1"), QStringLiteral("Native OSG building tile content URI is not local/portable: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片引用的资源缺失：%1"), QStringLiteral("Native OSG building tile referenced resource is missing: %1")},
        {QStringLiteral("本地 OSG 建筑瓦片集通过原生仅本地资源格式检查。"), QStringLiteral("Local OSG building tileset passes the native local-only contract checks.")},
        {QStringLiteral("本地 OSG 建筑瓦片集在接入渲染前需要检查。"), QStringLiteral("Local OSG building tileset needs attention before renderer integration.")},
        {QStringLiteral("%1 -> layer buildings -> 仅生成数据；默认安全本地地图模板不渲染此图层"), QStringLiteral("%1 -> layer buildings -> generated data only; not rendered by the safe default full-local earth template")},
        {QStringLiteral("%1 -> layer places -> 仅生成数据；默认安全本地地图模板不渲染此图层"), QStringLiteral("%1 -> layer places -> generated data only; not rendered by the safe default full-local earth template")},
        {QStringLiteral("Natural Earth 的 VRT 或栅格数据不完整。"), QStringLiteral("Natural Earth VRT/raster is incomplete.")},
        {QStringLiteral("没有可用的 Copernicus DEM 或 SRTM VRT。"), QStringLiteral("No Copernicus DEM or SRTM VRT is available.")},
        {QStringLiteral("缺少 Copernicus 完整本地地图模板。"), QStringLiteral("Copernicus full-local earth template is missing.")},
        {QStringLiteral("缺少 SRTM 完整本地地图模板。"), QStringLiteral("SRTM full-local earth template is missing.")},
        {QStringLiteral("缺少 OSM GeoPackage：%1"), QStringLiteral("Missing OSM GeoPackage: %1")},
        {QStringLiteral("本地实景三维 > Copernicus DEM > SRTM > Natural Earth > 本地网格"), QStringLiteral("Real 3D local > Copernicus DEM > SRTM > Natural Earth > Local grid")},
        {QStringLiteral("就绪"), QStringLiteral("ready")},
        {QStringLiteral("Natural Earth 底图：%1"), QStringLiteral("Natural Earth background: %1")},
        {QStringLiteral("DEM 地形：%1"), QStringLiteral("Terrain DEM: %1")},
        {QStringLiteral("OSM 矢量文件：%1（%2/4）；安全渲染图层：%3"), QStringLiteral("OSM vector files: %1 (%2/4); safe rendered layers: %3")},
        {QStringLiteral("水系、道路"), QStringLiteral("water, roads")},
        {QStringLiteral("可选影像叠加层：%1（%2/3）"), QStringLiteral("Optional imagery overlays: %1 (%2/3)")},
        {QStringLiteral("可从菜单加载"), QStringLiteral("menu ready")},
        {QStringLiteral("菜单未就绪"), QStringLiteral("not menu ready")},
        {QStringLiteral("可选原生 OSG 建筑瓦片：%1"), QStringLiteral("Optional native OSG building tiles: %1")},
        {QStringLiteral("格式有效"), QStringLiteral("contract valid")},
        {QStringLiteral("需要检查"), QStringLiteral("needs attention")},
        {QStringLiteral("未配置"), QStringLiteral("not configured")},
        {QStringLiteral("本地实景三维地图：%1"), QStringLiteral("Real 3D local map: %1")},
        {QStringLiteral("未就绪"), QStringLiteral("not ready")},
        {QStringLiteral("杭州西湖实景三维已就绪：已选择 Sentinel-2 影像、%1 高程、OSM 地理要素和本地建筑瓦片。"), QStringLiteral("Ready for Hangzhou Xihu real 3D: Sentinel-2 imagery, %1 elevation, OSM context, and local building tiles are selected.")},
        {QStringLiteral("完整离线地图已就绪：已选择 Natural Earth、%1 高程及安全的 OSM 水系和道路图层。"), QStringLiteral("Ready for full offline local map: Natural Earth, %1 elevation, and safe OSM water/road context are selected.")},
        {QStringLiteral("OSM 建筑和地名已准备好供诊断使用，但不会自动渲染，以免全国范围的标签和建筑导致地图卡顿。"), QStringLiteral("OSM buildings and places are prepared for diagnostics, but are not auto-rendered because full-country labels/buildings can stall the 3D map.")},
        {QStringLiteral("可选：准备 Sentinel-2、Landsat 或 OpenAerialMap GeoTIFF VRT，用于高分辨率影像叠加。"), QStringLiteral("Optional: prepare Sentinel-2, Landsat, or OpenAerialMap GeoTIFF VRTs for high-resolution imagery overlays.")},
        {QStringLiteral("可选：将 VaporView 原生 OSG 建筑瓦片集放入 resources/maps/tiles3d/local/，用于预览诊断。"), QStringLiteral("Optional: place a VaporView native OSG building tileset under resources/maps/tiles3d/local/ for preview diagnostics.")},
        {QStringLiteral("带地形的离线地图已就绪：已选择 Natural Earth 和 %1 高程；OSM 矢量数据不完整。"), QStringLiteral("Ready for terrain-backed offline map: Natural Earth and %1 elevation are selected; OSM vectors are not complete.")},
        {QStringLiteral("使用 scripts/prepare-osm-local-data.py 生成全部四个本地 OSM GeoPackage，以启用完整本地地图。"), QStringLiteral("Generate all four local OSM GeoPackages with scripts/prepare-osm-local-data.py to enable Full local map.")},
        {QStringLiteral("命令：python scripts/prepare-osm-local-data.py resources/maps/osm/local_extract.osm.pbf --overwrite"), QStringLiteral("Command: python scripts/prepare-osm-local-data.py resources/maps/osm/local_extract.osm.pbf --overwrite")},
        {QStringLiteral("验证：python scripts/prepare-osm-local-data.py resources/maps/osm/local_extract.osm.pbf --check"), QStringLiteral("Validate: python scripts/prepare-osm-local-data.py resources/maps/osm/local_extract.osm.pbf --check")},
        {QStringLiteral("缺少 OSM 文件：%1"), QStringLiteral("Missing OSM files: %1")},
        {QStringLiteral("仅离线视觉底图就绪：已选择 Natural Earth，但没有真实 DEM 地形。"), QStringLiteral("Ready for offline visual background only: Natural Earth is selected, but no real DEM terrain is available.")},
        {QStringLiteral("将 Copernicus DEM GLO-30 GeoTIFF 瓦片放入 resources/maps/terrain/copernicus_dem_glo30/，然后运行 scripts/prepare-demo-dem.py。"), QStringLiteral("Place Copernicus DEM GLO-30 GeoTIFF tiles under resources/maps/terrain/copernicus_dem_glo30/ and run scripts/prepare-demo-dem.py.")},
        {QStringLiteral("命令：python scripts/prepare-demo-dem.py"), QStringLiteral("Command: python scripts/prepare-demo-dem.py")},
        {QStringLiteral("Copernicus DEM 不可用时，可使用 resources/maps/terrain/srtm/ 中的 SRTM 作为备用。"), QStringLiteral("Use SRTM under resources/maps/terrain/srtm/ as a fallback when Copernicus DEM is unavailable.")},
        {QStringLiteral("SRTM 备用命令：python scripts/prepare-demo-dem.py --srtm"), QStringLiteral("SRTM fallback command: python scripts/prepare-demo-dem.py --srtm")},
        {QStringLiteral("仅能回退到本地网格：没有完整的离线 Natural Earth 数据集。"), QStringLiteral("Local grid fallback only: no complete offline Natural Earth dataset is available.")},
        {QStringLiteral("打开“地图资源”读取 HTTP 清单并下载 Natural Earth 底图。"), QStringLiteral("Open Map resources to read an HTTP manifest and download the Natural Earth background.")},
        {QStringLiteral("开发或离线准备可使用 scripts/download-natural-earth-map.ps1。"), QStringLiteral("For developer/offline preparation, scripts/download-natural-earth-map.ps1 remains available.")},
        {QStringLiteral("命令：powershell -ExecutionPolicy Bypass -File scripts/download-natural-earth-map.ps1"), QStringLiteral("Command: powershell -ExecutionPolicy Bypass -File scripts/download-natural-earth-map.ps1")},
        {QStringLiteral("然后添加 Copernicus DEM 或 SRTM VRT，以提供真实地形高程。"), QStringLiteral("Then add Copernicus DEM or SRTM VRTs for real terrain elevation.")},
        {QStringLiteral("DEM 命令：python scripts/prepare-demo-dem.py"), QStringLiteral("DEM command: python scripts/prepare-demo-dem.py")},
        {QStringLiteral("所选模式所需地图数据已就绪，没有阻塞项。"), QStringLiteral("No required map-data blockers remain for the selected mode.")},
        {QStringLiteral("未找到可用地图根目录；仅使用本地网格。"), QStringLiteral("No usable map root found; using local grid only.")},
        {QStringLiteral("完整本地地图"), QStringLiteral("Full local map")},
        {QStringLiteral("仅本地网格"), QStringLiteral("Local grid only")},
        {QStringLiteral("为加快三维地图启动，原生 OSG 建筑瓦片格式校验已延后。"), QStringLiteral("Native OSG building tileset contract validation is deferred for fast 3D Map startup.")},
        {QStringLiteral("已检测到可选原生 OSG 建筑瓦片集；主动加载渲染或资源时将执行格式校验。"), QStringLiteral("Optional native OSG building tileset detected; contract validation will run when rendering/resources are explicitly loaded.")},
        {QStringLiteral("已检测到可选本地高分辨率影像 VRT；可使用本地影像菜单加载已就绪的叠加层。"), QStringLiteral("Optional local high-resolution imagery VRTs detected; use the local imagery toolbar menu to load menu-ready overlays.")},
        {QStringLiteral("已检测到本地高分辨率影像 VRT，但缺少菜单所需的匹配地图场景模板。"), QStringLiteral("Optional local high-resolution imagery VRTs detected, but no matching imagery earth templates are available for the toolbar menu.")},
        {QStringLiteral("已检测到原生 OSG 建筑瓦片集，并通过仅本地资源格式检查。"), QStringLiteral("Optional native OSG building tileset detected and passed local-only contract checks.")},
        {QStringLiteral("已检测到原生 OSG 建筑瓦片集，但接入渲染前仍需检查。"), QStringLiteral("Optional native OSG building tileset detected but needs attention before renderer integration.")},
        {QStringLiteral("杭州西湖 Sentinel-2 影像、Copernicus DEM、OSM 地理要素及本地三维建筑瓦片。"), QStringLiteral("Hangzhou Xihu Sentinel-2 imagery, Copernicus DEM, OSM context, and local 3D building tiles.")},
        {QStringLiteral("已选择杭州西湖实景三维本地地图，包含 Sentinel-2 影像和本地建筑瓦片。"), QStringLiteral("Selected Hangzhou Xihu real-3D local map with Sentinel-2 imagery and local building tiles.")},
        {QStringLiteral("Natural Earth 底图、本地 DEM 及本地 OSM 矢量 GeoPackage。"), QStringLiteral("Natural Earth background, local DEM, and local OSM vector GeoPackages.")},
        {QStringLiteral("已选择完整本地地图，包含安全的离线 OSM 水系和道路图层及 %1 高程。"), QStringLiteral("Selected full local map with safe offline OSM water/road layers and %1 elevation.")},
        {QStringLiteral("OSM 建筑和地名标签已生成为 GeoPackage；默认不渲染，以避免中文字形缺失和缩放卡顿。"), QStringLiteral("OSM buildings and place labels are available as generated GeoPackages but are not rendered by default to avoid CJK glyph boxes and zoom-time stalls.")},
        {QStringLiteral("Natural Earth 底图及本地 Copernicus DEM 高程。"), QStringLiteral("Natural Earth background with local Copernicus DEM elevation.")},
        {QStringLiteral("已选择 Copernicus DEM GLO-30 本地高程。"), QStringLiteral("Selected Copernicus DEM GLO-30 local elevation.")},
        {QStringLiteral("完整本地 OSM 数据可用，但自动选择优先使用 DEM 模板。"), QStringLiteral("Full local OSM data is available but automatic selection prioritizes DEM templates.")},
        {QStringLiteral("完整本地地图模板存在，但缺少一个或多个 OSM GeoPackage。"), QStringLiteral("Full local map template exists, but one or more OSM GeoPackages are missing.")},
        {QStringLiteral("Natural Earth 底图及本地 SRTM 高程。"), QStringLiteral("Natural Earth background with local SRTM elevation.")},
        {QStringLiteral("已选择 SRTM 本地高程作为备用。"), QStringLiteral("Selected SRTM local elevation fallback.")},
        {QStringLiteral("不含地形高程的 Natural Earth 离线视觉底图。"), QStringLiteral("Natural Earth offline visual background without terrain elevation.")},
        {QStringLiteral("已选择 Natural Earth 离线底图。"), QStringLiteral("Selected Natural Earth offline background.")},
        {QStringLiteral("Natural Earth 仅提供影像；没有可用的真实 DEM 地形。"), QStringLiteral("Natural Earth is imagery only; no real DEM terrain is available.")},
        {QStringLiteral("未找到完整本地地图数据；使用内置本地网格回退。"), QStringLiteral("No complete local map set found; use the built-in local grid fallback.")},
        {QStringLiteral("此根目录下未找到完整离线地图数据。"), QStringLiteral("No complete offline map set found for this root.")},
        {QStringLiteral("模式： %1 (%2)"), QStringLiteral("Mode: %1 (%2)")},
        {QStringLiteral("底图优先级： %1"), QStringLiteral("Base map priority: %1")},
        {QStringLiteral("Copernicus DEM > SRTM > Natural Earth > 本地网格"), QStringLiteral("Copernicus DEM > SRTM > Natural Earth > Local grid")},
        {QStringLiteral("已选底图模式： %1 (%2)"), QStringLiteral("Selected base mode: %1 (%2)")},
        {QStringLiteral("<未评估>"), QStringLiteral("<not evaluated>")},
        {QStringLiteral("已选底图场景文件： %1"), QStringLiteral("Selected base earth file: %1")},
        {QStringLiteral("<无>"), QStringLiteral("<none>")},
        {QStringLiteral("说明： %1"), QStringLiteral("Description: %1")},
        {QStringLiteral("地图场景文件： %1"), QStringLiteral("Earth file: %1")},
        {QStringLiteral("地图场景加载："), QStringLiteral("Earth load:")},
        {QStringLiteral("  请求路径： %1"), QStringLiteral("  Requested path: %1")},
        {QStringLiteral("  已尝试加载： %1"), QStringLiteral("  Attempted: %1")},
        {QStringLiteral("是"), QStringLiteral("yes")},
        {QStringLiteral("否"), QStringLiteral("no")},
        {QStringLiteral("  已加载： %1"), QStringLiteral("  Loaded: %1")},
        {QStringLiteral("  纹理回退： %1"), QStringLiteral("  Textured fallback: %1")},
        {QStringLiteral("  图层： %1/%2 已打开"), QStringLiteral("  Layers: %1/%2 open")},
        {QStringLiteral("  失败原因或说明： %1"), QStringLiteral("  Failure/note: %1")},
        {QStringLiteral("  图层详情："), QStringLiteral("  Layer details:")},
        {QStringLiteral("本地原生 OSG 建筑加载："), QStringLiteral("Local native OSG building load:")},
        {QStringLiteral("  已清除原有预览： %1"), QStringLiteral("  Cleared previous preview: %1")},
        {QStringLiteral("  数据块： %1/%2 已加载，%3 失败"), QStringLiteral("  Payloads: %1/%2 loaded, %3 failed")},
        {QStringLiteral("  节点： %1"), QStringLiteral("  Node: %1")},
        {QStringLiteral("飞行器模型："), QStringLiteral("Aircraft model:")},
        {QStringLiteral("  内置标记： %1"), QStringLiteral("  Built-in marker: %1")},
        {QStringLiteral("渲染性能："), QStringLiteral("Render performance:")},
        {QStringLiteral("  采样点： %1 可见 / %2 总计 / %3 隐藏"), QStringLiteral("  Samples: %1 visible / %2 total / %3 hidden")},
        {QStringLiteral("  最大可见采样点数： %1"), QStringLiteral("  Max visible samples: %1")},
        {QStringLiteral("  轨迹分段： %1 段 × %2 点"), QStringLiteral("  Trajectory segments: %1 x %2 samples")},
        {QStringLiteral("  CPU 单帧耗时 ms（非 GPU 耗时）： %1"), QStringLiteral("  CPU frame ms (not GPU time): %1")},
        {QStringLiteral("  显示帧间隔 P95 ms（含空闲等待）： %1"), QStringLiteral("  Presented frame interval P95 ms (includes idle pacing): %1")},
        {QStringLiteral("  绘制结束到帧交换耗时 ms： %1"), QStringLiteral("  Paint end to frameSwapped ms: %1")},
        {QStringLiteral("  osgEarth 等待/运行任务数（整个进程）： %1/%2"), QStringLiteral("  osgEarth jobs pending/running (process-wide): %1/%2")},
        {QStringLiteral("  卫星影像请求/失败次数（不含缓存命中）： %1/%2"), QStringLiteral("  Satellite source requests/failures (cache hits excluded): %1/%2")},
        {QStringLiteral("  轨迹更新耗时 ms： %1"), QStringLiteral("  Track update ms: %1")},
        {QStringLiteral("轨迹质量："), QStringLiteral("Trajectory quality:")},
        {QStringLiteral("  可见轨迹线采样点： %1"), QStringLiteral("  Visible line samples: %1")},
        {QStringLiteral("  可见标记采样点： %1"), QStringLiteral("  Visible marker samples: %1")},
        {QStringLiteral("  固定解： %1"), QStringLiteral("  Fixed: %1")},
        {QStringLiteral("  浮点解： %1"), QStringLiteral("  Float: %1")},
        {QStringLiteral("  差分定位： %1"), QStringLiteral("  DGPS: %1")},
        {QStringLiteral("  单点定位： %1"), QStringLiteral("  Single: %1")},
        {QStringLiteral("  未知： %1"), QStringLiteral("  Unknown: %1")},
        {QStringLiteral("  无效或不可用： %1"), QStringLiteral("  Invalid/unusable: %1")},
        {QStringLiteral("  跳变标记： %1"), QStringLiteral("  Jump markers: %1")},
        {QStringLiteral("轨迹数据："), QStringLiteral("Track data:")},
        {QStringLiteral("  来源： %1"), QStringLiteral("  Source: %1")},
        {QStringLiteral("  回放状态： %1"), QStringLiteral("  Replay state: %1")},
        {QStringLiteral("  回放位置： %1/%2"), QStringLiteral("  Replay position: %1/%2")},
        {QStringLiteral("  回放速度： %1x"), QStringLiteral("  Replay speed: %1x")},
        {QStringLiteral("  回放时间： %1"), QStringLiteral("  Replay time: %1")},
        {QStringLiteral("  最新记录时间戳 us： %1"), QStringLiteral("  Latest record timestamp us: %1")},
        {QStringLiteral("  最新设备时间戳 us： %1"), QStringLiteral("  Latest device timestamp us: %1")},
        {QStringLiteral("  姿态来源： %1"), QStringLiteral("  Attitude source: %1")},
        {QStringLiteral("  跟随飞行器： %1"), QStringLiteral("  Follow aircraft: %1")},
        {QStringLiteral("  高度基准： %1"), QStringLiteral("  Height reference: %1")},
        {QStringLiteral("  定位质量： %1"), QStringLiteral("  Fix quality: %1")},
        {QStringLiteral("  高度使用说明： %1"), QStringLiteral("  Height safety note: %1")},
        {QStringLiteral("  高度转换： %1"), QStringLiteral("  Height conversion: %1")},
        {QStringLiteral("  备注： %1"), QStringLiteral("  Note: %1")},
        {QStringLiteral("  最近丢弃数据来源： %1"), QStringLiteral("  Last drop source: %1")},
        {QStringLiteral("  最近丢弃原因： %1"), QStringLiteral("  Last drop reason: %1")},
        {QStringLiteral("  最近丢弃记录时间戳 us： %1"), QStringLiteral("  Last drop record timestamp us: %1")},
        {QStringLiteral("视角： %1"), QStringLiteral("Camera: %1")},
        {QStringLiteral("图层摘要："), QStringLiteral("Layer summary:")},
        {QStringLiteral("  就绪状态： %1"), QStringLiteral("  Readiness: %1")},
        {QStringLiteral("  就绪检查："), QStringLiteral("  Readiness checks:")},
        {QStringLiteral("  后续操作："), QStringLiteral("  Next steps:")},
        {QStringLiteral("  本地网格回退： %1%2"), QStringLiteral("  Local grid fallback: %1%2")},
        {QStringLiteral("不可用"), QStringLiteral("unavailable")},
        {QStringLiteral("（使用中）"), QStringLiteral(" (active)")},
        {QStringLiteral("（备用）"), QStringLiteral(" (standby)")},
        {QStringLiteral("  已选 DEM： %1"), QStringLiteral("  Selected DEM: %1")},
        {QStringLiteral("  OSM 矢量数据： %1 (已找到 %2/4 个文件)"), QStringLiteral("  OSM vectors: %1 (%2/4 files found)")},
        {QStringLiteral("  已选 OSM： %1"), QStringLiteral("  Selected OSM: %1")},
        {QStringLiteral("  已选完整本地地图场景： %1"), QStringLiteral("  Selected full-local earth: %1")},
        {QStringLiteral("<未选择>"), QStringLiteral("<not selected>")},
        {QStringLiteral("  可选本地影像 VRT： 已找到 %1/3"), QStringLiteral("  Optional local imagery VRTs: %1/3 found")},
        {QStringLiteral("  可从菜单加载的本地影像： %1/3"), QStringLiteral("  Optional local imagery menu-ready overlays: %1/3")},
        {QStringLiteral("  本地影像菜单："), QStringLiteral("  Local imagery menu:")},
        {QStringLiteral("缺少 VRT 或场景模板"), QStringLiteral("missing VRT or earth template")},
        {QStringLiteral("已找到"), QStringLiteral("found")},
        {QStringLiteral("  可选原生 OSG 建筑瓦片： %1"), QStringLiteral("  Optional native OSG building tiles: %1")},
        {QStringLiteral("  原生 OSG 建筑瓦片格式约定： %1"), QStringLiteral("  Native OSG building tiles contract: %1")},
        {QStringLiteral("有效"), QStringLiteral("valid")},
        {QStringLiteral("未检查"), QStringLiteral("not checked")},
        {QStringLiteral("  实景三维本地地图： %1"), QStringLiteral("  Real 3D local map: %1")},
        {QStringLiteral("  实景三维场景： %1"), QStringLiteral("  Real 3D earth: %1")},
        {QStringLiteral("当前工作目录： %1"), QStringLiteral("Current working directory: %1")},
        {QStringLiteral("<未知>"), QStringLiteral("<unknown>")},
        {QStringLiteral("项目根目录： %1"), QStringLiteral("Project root: %1")},
        {QStringLiteral("地图根目录： %1"), QStringLiteral("Maps root: %1")},
        {QStringLiteral("完整本地 Copernicus 场景： %1"), QStringLiteral("Full local Copernicus earth: %1")},
        {QStringLiteral("完整本地 SRTM 场景： %1"), QStringLiteral("Full local SRTM earth: %1")},
        {QStringLiteral("Natural Earth 纹理： %1"), QStringLiteral("Natural Earth texture: %1")},
        {QStringLiteral("Natural Earth 栅格： %1"), QStringLiteral("Natural Earth raster: %1")},
        {QStringLiteral("OSM 道路： %1"), QStringLiteral("OSM roads: %1")},
        {QStringLiteral("OSM 水系： %1"), QStringLiteral("OSM water: %1")},
        {QStringLiteral("OSM 建筑： %1"), QStringLiteral("OSM buildings: %1")},
        {QStringLiteral("OSM 地名： %1"), QStringLiteral("OSM places: %1")},
        {QStringLiteral("OSM 图层约定："), QStringLiteral("OSM layer contract:")},
        {QStringLiteral("Sentinel-2 影像 VRT： %1"), QStringLiteral("Sentinel-2 imagery VRT: %1")},
        {QStringLiteral("Landsat 影像 VRT： %1"), QStringLiteral("Landsat imagery VRT: %1")},
        {QStringLiteral("OpenAerialMap 影像 VRT： %1"), QStringLiteral("OpenAerialMap imagery VRT: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片集： %1"), QStringLiteral("Native OSG building tileset: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片有效： %1"), QStringLiteral("Native OSG building tiles valid: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片引用资源数： %1"), QStringLiteral("Native OSG building tile referenced resources: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片资源 URI："), QStringLiteral("Native OSG building tile resource URIs:")},
        {QStringLiteral("原生 OSG 建筑瓦片非本地或不支持的 URI："), QStringLiteral("Native OSG building tile non-local/unsupported URIs:")},
        {QStringLiteral("原生 OSG 建筑瓦片缺失资源："), QStringLiteral("Native OSG building tile missing resources:")},
        {QStringLiteral("原生 OSG 建筑瓦片诊断："), QStringLiteral("Native OSG building tile diagnostics:")},
        {QStringLiteral("OSG 插件路径： %1"), QStringLiteral("OSG plugin path: %1")},
        {QStringLiteral("<未找到>"), QStringLiteral("<not found>")},
        {QStringLiteral("<未设置>"), QStringLiteral("<not set>")},
        {QStringLiteral("osgEarth 环境变量："), QStringLiteral("osgEarth environment:")},
        {QStringLiteral("  - <均未设置>"), QStringLiteral("  - <none set>")},
        {QStringLiteral("已找到文件："), QStringLiteral("Found files:")},
        {QStringLiteral("缺失文件："), QStringLiteral("Missing files:")},
        {QStringLiteral("完整本地地图阻塞项："), QStringLiteral("Full local map blockers:")},
        {QStringLiteral("警告："), QStringLiteral("Warnings:")},
        {QStringLiteral("诊断信息："), QStringLiteral("Diagnostics:")},
        {QStringLiteral("osgDB::readNodeFile 返回空节点。"), QStringLiteral("osgDB::readNodeFile returned null.")},
        {QStringLiteral("手动创建的 Natural Earth 纹理地球回退（不含 osgEarth MapNode）。"), QStringLiteral("Manual Natural Earth textured globe fallback (no osgEarth MapNode).")},
        {QStringLiteral("已加载 OSG 节点，但未找到 osgEarth MapNode。"), QStringLiteral("Loaded OSG node, but no osgEarth MapNode was found.")},
        {QStringLiteral("%1 | 已打开=%2 | 状态=%3"), QStringLiteral("%1 | open=%2 | status=%3")},
        {QStringLiteral("原生 OSG 建筑瓦片集文件不存在。"), QStringLiteral("Native OSG building tileset file does not exist.")},
        {QStringLiteral("原生 OSG 建筑瓦片索引超过 64 MiB 安全上限。"), QStringLiteral("Native OSG building tile index exceeds the 64 MiB safety limit.")},
        {QStringLiteral("原生 OSG 建筑瓦片索引缺少根瓦片对象。"), QStringLiteral("Native OSG building tile index does not contain a root tile object.")},
        {QStringLiteral("不支持此建筑数据格式。加载器仅接受 vaporview-osg-native-building-tiles，不支持通用 Cesium 3D Tiles。"), QStringLiteral("Unsupported building payload contract. This loader accepts only vaporview-osg-native-building-tiles, not generic Cesium 3D Tiles.")},
        {QStringLiteral("已拒绝非本地瓦片资源 URI：%1"), QStringLiteral("Rejected non-local tile payload URI: %1")},
        {QStringLiteral("本地瓦片数据加载失败：%1"), QStringLiteral("Failed to load local tile payload: %1")},
        {QStringLiteral("原生 OSG 建筑瓦片索引超过遍历安全上限；已保留原预览。"), QStringLiteral("Native OSG building tile index exceeds the traversal safety limit; previous preview was preserved.")},
        {QStringLiteral("本地瓦片集没有可加载的数据块。"), QStringLiteral("Local tileset did not contain a loadable payload.")},
        {QStringLiteral("本地瓦片集加载不完整（%1/%2 个数据块）；已保留原预览。%3"), QStringLiteral("Local tileset load was incomplete (%1/%2 payloads); previous preview was preserved. %3")},
        {QStringLiteral("已加载 %1 个数据块，共 %2 个瓦片"), QStringLiteral("%1 loaded payloads across %2 tiles")},
        {QStringLiteral("未配置 %1；使用内置标记。"), QStringLiteral("%1 not configured; using built-in marker.")},
        {QStringLiteral("%1 文件不存在；使用内置标记。"), QStringLiteral("%1 file does not exist; using built-in marker.")},
        {QStringLiteral("osgDB::readNodeFile 无法读取 %1；使用内置标记。"), QStringLiteral("%1 could not be read by osgDB::readNodeFile; using built-in marker.")},
        {QStringLiteral("%1 个子节点，包围球半径 %2"), QStringLiteral("%1 children, bound radius %2")},
        {QStringLiteral("未应用天地图卫星影像：未配置密钥。"), QStringLiteral("Tianditu Satellite imagery not applied: no key configured.")},
        {QStringLiteral("天地图源级别：%1–%2；不使用第 0 级占位图。"), QStringLiteral("Tianditu source levels: %1-%2; level 0 placeholder excluded.")},
        {QStringLiteral("天地图卫星影像已添加到图层索引 %1%2。"), QStringLiteral("Tianditu Satellite imagery added at layer index %1%2.")},
        {QStringLiteral("场景根节点尚未初始化。"), QStringLiteral("Scene root is not initialized.")},
        {QStringLiteral("地形细节：可见区域优先的屏幕空间 LOD，128 px 瓦片阈值，低视角自适应裁剪和细节级别。"), QStringLiteral("Terrain detail: visible-first screen-space LOD, 128 px tile threshold, low-angle adaptive clipping and LOD.")},
        {QStringLiteral("已替换原地图场景。"), QStringLiteral("Replaced previous Earth scene.")},
        {QStringLiteral("已应用 WGS84 椭球高。"), QStringLiteral("WGS84 ellipsoid height applied.")},
        {QStringLiteral("基础地理底图"), QStringLiteral("Geographic base map")},
        {QStringLiteral("卫星遥感影像"), QStringLiteral("Satellite imagery")},
        {QStringLiteral("数字高程模型（DEM）"), QStringLiteral("Digital elevation model (DEM)")},
        {QStringLiteral("三维建筑模型"), QStringLiteral("3D buildings")},
        {QStringLiteral("水系"), QStringLiteral("Water features")},
        {QStringLiteral("道路网络"), QStringLiteral("Road network")},
        {QStringLiteral("飞行任务要素（轨迹、测点、标记）"), QStringLiteral("Flight elements (track, samples, markers)")},
        {QStringLiteral("图层"), QStringLiteral("Layers")},
        {QStringLiteral("地图图层"), QStringLiteral("Map layers")},
        {QStringLiteral("地图文件"), QStringLiteral("Map files")},
        {QStringLiteral("地图诊断"), QStringLiteral("Map diagnostics")},
        {QStringLiteral("地图资源"), QStringLiteral("Map resources")},
        {QStringLiteral("视角与诊断"), QStringLiteral("View and diagnostics")},
        {QStringLiteral("飞机模型"), QStringLiteral("Aircraft model")},
        {QStringLiteral("显示设置"), QStringLiteral("Display settings")},
        {QStringLiteral("显示"), QStringLiteral("Display")},
        {QStringLiteral("更多"), QStringLiteral("More")},
        {QStringLiteral("打开 Session"), QStringLiteral("Open session")},
        {QStringLiteral("选择 Session 目录"), QStringLiteral("Select session folder")},
        {QStringLiteral("加载 Session"), QStringLiteral("Load session")},
        {QStringLiteral("清空轨迹"), QStringLiteral("Clear track")},
        {QStringLiteral("加载 Earth 文件"), QStringLiteral("Load Earth file")},
        {QStringLiteral("本地影像"), QStringLiteral("Local imagery")},
        {QStringLiteral("本地 OSG 建筑"), QStringLiteral("Local OSG buildings")},
        {QStringLiteral("清除 OSG 建筑"), QStringLiteral("Clear OSG buildings")},
        {QStringLiteral("重载最佳本地地图"), QStringLiteral("Reload best local map")},
        {QStringLiteral("加载飞机模型"), QStringLiteral("Load aircraft model")},
        {QStringLiteral("内置飞机标记"), QStringLiteral("Built-in aircraft marker")},
        {QStringLiteral("飞到飞机"), QStringLiteral("Fly to aircraft")},
        {QStringLiteral("定位到飞机"), QStringLiteral("Locate aircraft")},
        {QStringLiteral("飞到轨迹"), QStringLiteral("Fly to track")},
        {QStringLiteral("重置视角"), QStringLiteral("Reset view")},
        {QStringLiteral("跟随"), QStringLiteral("Follow")},
        {QStringLiteral("跟随飞机"), QStringLiteral("Follow aircraft")},
        {QStringLiteral("播放"), QStringLiteral("Play")},
        {QStringLiteral("暂停"), QStringLiteral("Pause")},
        {QStringLiteral("停止回放"), QStringLiteral("Stop playback")},
        {QStringLiteral("重新扫描"), QStringLiteral("Rescan")},
        {QStringLiteral("可见点数量"), QStringLiteral("Visible sample limit")},
        {QStringLiteral("最大可见轨迹点数"), QStringLiteral("Maximum visible samples")},
        {QStringLiteral("可见点 "), QStringLiteral("Samples ")},
        {QStringLiteral(" 点"), QStringLiteral(" samples")},
        {QStringLiteral("轨迹线"), QStringLiteral("Track line")},
        {QStringLiteral("轨迹点"), QStringLiteral("Track points")},
        {QStringLiteral("线宽"), QStringLiteral("Line width")},
        {QStringLiteral("线宽 "), QStringLiteral("Width ")},
        {QStringLiteral("点大小"), QStringLiteral("Point size")},
        {QStringLiteral("点 "), QStringLiteral("Point ")},
        {QStringLiteral("热力指标"), QStringLiteral("Heat metric")},
        {QStringLiteral("轨迹来源"), QStringLiteral("Track source")},
        {QStringLiteral("原始"), QStringLiteral("Original")},
        {QStringLiteral("PPK 修正"), QStringLiteral("PPK corrected")},
        {QStringLiteral("热力范围"), QStringLiteral("Heat range")},
        {QStringLiteral("配色"), QStringLiteral("Palette")},
        {QStringLiteral("峰值"), QStringLiteral("Peak")},
        {QStringLiteral("湿度"), QStringLiteral("Humidity")},
        {QStringLiteral("温度"), QStringLiteral("Temperature")},
        {QStringLiteral("气压"), QStringLiteral("Pressure")},
        {QStringLiteral("当前图层"), QStringLiteral("Current layer")},
        {QStringLiteral("当前图层未加载，数据可用时将在加载后显示"), QStringLiteral("Layer not loaded; available data will appear after loading")},
        {QStringLiteral("%1: -- · 无有效数据"), QStringLiteral("%1: -- - No valid data")},
        {QStringLiteral(" (已自动定位轨迹)"), QStringLiteral(" (track focused automatically)")},
        {QStringLiteral("%1：已设为显示，当前图层加载对应数据后自动生效"), QStringLiteral("%1: enabled; takes effect when layer data is loaded")},
        {QStringLiteral("正在检查并启动 3D 渲染…"), QStringLiteral("Checking and starting 3D rendering...")},
        {QStringLiteral("正在创建 3D 渲染视图..."), QStringLiteral("Creating 3D render view...")},
        {QStringLiteral("无法创建 3D 渲染视图。"), QStringLiteral("Unable to create the 3D render view.")},
        {QStringLiteral("3D 渲染已停止：%1\n可关闭窗口或查看地图文件状态。"), QStringLiteral("3D rendering stopped: %1\nClose the window or inspect map files.")},
        {QStringLiteral("3D 渲染启动失败"), QStringLiteral("3D rendering failed")},
        {QStringLiteral("正在读取 Session 数据。"), QStringLiteral("Reading session data.")},
        {QStringLiteral("Session 轨迹加载失败。"), QStringLiteral("Session track loading failed.")},
        {QStringLiteral("无法读取轨迹: %1"), QStringLiteral("Unable to read track: %1")},
        {QStringLiteral("地图偏好已恢复。"), QStringLiteral("Map preferences restored.")},
        {QStringLiteral("文件路径"), QStringLiteral("File path")},
        {QStringLiteral("状态"), QStringLiteral("Status")},
        {QStringLiteral("不可读 / 非文件"), QStringLiteral("Unreadable / not a file")},
        {QStringLiteral("地图目录：%1\n当前选择：%2\n共 %3 个文件 · 就绪 %4 · 缺失 %5 · 异常 %6"), QStringLiteral("Map folder: %1\nSelection: %2\n%3 files - %4 ready - %5 missing - %6 invalid")},
        {QStringLiteral("就绪表示本地文件存在且可读，不代表已加载或内容完整；可选数据缺失不影响其他地图使用。完整加载信息可查看“地图诊断”。"), QStringLiteral("Ready means the local file exists and is readable, not that it is loaded or complete. Missing optional data does not affect other maps. See Map diagnostics for load details.")},
        {QStringLiteral("3D 地图资源"), QStringLiteral("3D map resources")},
        {QStringLiteral("HTTP 清单"), QStringLiteral("HTTP manifest")},
        {QStringLiteral("下载选中"), QStringLiteral("Download selected")},
        {QStringLiteral("删除选中"), QStringLiteral("Remove selected")},
        {QStringLiteral("删除地图资源"), QStringLiteral("Remove map resource")},
        {QStringLiteral("地图资源操作失败"), QStringLiteral("Map resource operation failed")},
        {QStringLiteral("大小"), QStringLiteral("Size")},
        {QStringLiteral("已安装"), QStringLiteral("Installed")},
        {QStringLiteral("未安装"), QStringLiteral("Not installed")},
        {QStringLiteral("版本"), QStringLiteral("Version")},
        {QStringLiteral("读取清单"), QStringLiteral("Read manifest")},
        {QStringLiteral("资源"), QStringLiteral("Resource")},
        {QStringLiteral("资源目录：%1"), QStringLiteral("Resource folder: %1")},
        {QStringLiteral("已重新扫描本地地图资源：%1"), QStringLiteral("Rescanned local map resources: %1")},
        {QStringLiteral("确定删除“%1”的本地文件吗？"), QStringLiteral("Remove local files for \"%1\"?")},
        {QStringLiteral("地图资源不会随安装包发布。下载完成后将按清单校验并放入本地 resources/maps。"), QStringLiteral("Map resources are distributed separately. Downloads are verified against the manifest and placed in local resources/maps.")},
        {QStringLiteral("查看本地地图文件及就绪、缺失状态"), QStringLiteral("Inspect local map files and availability")},
        {QStringLiteral("读取、下载和校验 3D 地图资源"), QStringLiteral("Read, download and verify 3D map resources")},
        {QStringLiteral("选择 3D 地图中显示的基础与专业地理图层"), QStringLiteral("Choose base and specialized map layers")},
        {QStringLiteral("全球地理背景、参考地表与网格"), QStringLiteral("Global background, reference surface and grid")},
        {QStringLiteral("Sentinel-2、Landsat、本地影像与天地图卫星影像"), QStringLiteral("Sentinel-2, Landsat, local and Tianditu satellite imagery")},
        {QStringLiteral("DEM 地形起伏与高程表达"), QStringLiteral("DEM terrain relief and elevation")},
        {QStringLiteral("本地原生 OSG 三维建筑覆盖层"), QStringLiteral("Local native OSG 3D building overlay")},
        {QStringLiteral("河流、湖泊等矢量水文要素"), QStringLiteral("Rivers, lakes and vector water features")},
        {QStringLiteral("道路与交通线状要素"), QStringLiteral("Roads and transport lines")},
        {QStringLiteral("飞行轨迹、采样点、事件标记与飞机模型"), QStringLiteral("Flight track, samples, events and aircraft model")},
        {QStringLiteral("3D 轨迹热力指标"), QStringLiteral("3D track heat metric")},
        {QStringLiteral("3D 轨迹热力配色"), QStringLiteral("3D track heat palette")},
        {QStringLiteral("选择本地 .osgb/.osg/.glb/.gltf 飞机模型"), QStringLiteral("Select a local .osgb/.osg/.glb/.gltf aircraft model")},
        {QStringLiteral("飞行任务要素（轨迹与飞行器）"), QStringLiteral("Flight elements (track and aircraft)")},
        {QStringLiteral("3D 轨迹热力调色板"), QStringLiteral("3D track heat palette")},
        {QStringLiteral("DEM 地形起伏与高程表面"), QStringLiteral("DEM terrain relief and elevation")},
        {QStringLiteral("Sentinel-2、Landsat、航空影像或天地图卫星影像"), QStringLiteral("Sentinel-2, Landsat, aerial or Tianditu satellite imagery")},
        {QStringLiteral("全球基础地理参考与地表纹理"), QStringLiteral("Global geographic reference and surface texture")},
        {QStringLiteral("当前可用"), QStringLiteral("Available now")},
        {QStringLiteral("当前场景未加载；数据可用时按此设置显示"), QStringLiteral("Not loaded in this scene; shown when data becomes available")},
        {QStringLiteral("本地原生 OSG 三维建筑叠加层"), QStringLiteral("Local native OSG 3D building overlay")},
        {QStringLiteral("河流、湖泊及其他水体要素"), QStringLiteral("Rivers, lakes and other water features")},
        {QStringLiteral("道路与交通网络要素"), QStringLiteral("Road and transport features")},
        {QStringLiteral("飞行轨迹、采样点与飞行器模型"), QStringLiteral("Flight track, samples and aircraft model")},
        {QStringLiteral("隐藏"), QStringLiteral("Hide")},
        {QStringLiteral("（静止）"), QStringLiteral(" (idle)")},
        {QStringLiteral("选择 3D 地图中显示的基础、专题与任务图层"), QStringLiteral("Choose base, thematic and mission layers")},
        {QStringLiteral("正在读取 Session 数据…"), QStringLiteral("Reading session data...")},
        {QStringLiteral("正在启动 3D 渲染视图..."), QStringLiteral("Starting 3D rendering...")},
        {QStringLiteral("3D 渲染已启动。"), QStringLiteral("3D rendering started.")},
        {QStringLiteral("3D 地图窗口已打开；点击“启动渲染”后加载地图。"), QStringLiteral("3D Map opened; start rendering to load the map.")},
        {QStringLiteral("已定位到完整轨迹。"), QStringLiteral("Focused the complete track.")},
        {QStringLiteral("已定位到飞机。"), QStringLiteral("Focused the aircraft.")},
        {QStringLiteral("视角已重置。"), QStringLiteral("View reset.")},
        {QStringLiteral("暂无轨迹可定位。"), QStringLiteral("No track to focus.")},
        {QStringLiteral("暂无飞机位置可定位。"), QStringLiteral("No aircraft position to focus.")},
        {QStringLiteral("已恢复内置飞机标记。"), QStringLiteral("Built-in aircraft marker restored.")},
        {QStringLiteral("正在后台加载 Earth 文件: %1"), QStringLiteral("Loading Earth file in background: %1")},
        {QStringLiteral("正在后台加载本地影像: %1"), QStringLiteral("Loading local imagery in background: %1")},
        {QStringLiteral("正在后台加载飞机模型: %1"), QStringLiteral("Loading aircraft model in background: %1")},
        {QStringLiteral("正在后台加载本地 3D 建筑..."), QStringLiteral("Loading local 3D buildings in background...")},
        {QStringLiteral("正在后台重载最佳本地地图: %1"), QStringLiteral("Reloading best local map in background: %1")},
        {QStringLiteral("已加载本地影像: %1%2"), QStringLiteral("Loaded local imagery: %1%2")},
        {QStringLiteral("已加载飞机模型: %1"), QStringLiteral("Loaded aircraft model: %1")},
        {QStringLiteral("已加载本地 OSG 建筑叠加层: %1 个 payload"), QStringLiteral("Loaded local OSG buildings: %1 payloads")},
        {QStringLiteral("已重载最佳本地地图: %1%2"), QStringLiteral("Reloaded best local map: %1%2")},
        {QStringLiteral("已自动加载 Earth 文件: %1"), QStringLiteral("Automatically loaded Earth file: %1")},
        {QStringLiteral("加载本地影像失败: %1"), QStringLiteral("Failed to load local imagery: %1")},
        {QStringLiteral("无法加载 Earth 文件: %1"), QStringLiteral("Unable to load Earth file: %1")},
        {QStringLiteral("无法加载飞机模型，已保留当前标记: %1"), QStringLiteral("Unable to load aircraft model; current marker preserved: %1")},
        {QStringLiteral("本地 3D 建筑加载失败: %1"), QStringLiteral("Local 3D building load failed: %1")},
        {QStringLiteral("本地影像不可用: %1"), QStringLiteral("Local imagery unavailable: %1")},
        {QStringLiteral("飞机模型加载失败，已保留当前标记: %1"), QStringLiteral("Aircraft model load failed; current marker preserved: %1")},
        {QStringLiteral("重载最佳本地地图失败，已保留当前地图: %1"), QStringLiteral("Map reload failed; current map preserved: %1")},
        {QStringLiteral("本地 OSG 建筑瓦片不可用或契约无效；请查看地图诊断"), QStringLiteral("Local OSG building tiles unavailable or invalid; see Map diagnostics")},
        {QStringLiteral("本地 OSG 建筑瓦片契约无效，请先查看地图诊断。"), QStringLiteral("Invalid local OSG building tile format; see Map diagnostics.")},
        {QStringLiteral("加载本地 OSG 建筑瓦片: %1"), QStringLiteral("Load local OSG building tiles: %1")},
        {QStringLiteral("加载 VaporView 原生 OSG 建筑瓦片；不支持通用 Cesium 3D Tiles"), QStringLiteral("Load VaporView native OSG building tiles; generic Cesium 3D Tiles are unsupported")},
        {QStringLiteral("清除当前本地 OSG 建筑叠加层"), QStringLiteral("Clear the current local OSG building overlay")},
        {QStringLiteral("清除自定义飞机模型设置并恢复内置标记"), QStringLiteral("Reset custom aircraft model and restore built-in marker")},
        {QStringLiteral("未找到可用的本地地图数据，已保留当前地图。"), QStringLiteral("No local map data available; current map preserved.")},
        {QStringLiteral("未找到默认 Earth 文件，当前显示本地 NED 网格。"), QStringLiteral("Default Earth file not found; showing local NED grid.")},
        {QStringLiteral("未配置天地图 Key，3D 地图保留本地离线影像。"), QStringLiteral("No Tianditu key configured; retaining local offline imagery.")},
        {QStringLiteral("天地图卫星影像加载失败，已保留当前本地影像。"), QStringLiteral("Tianditu imagery load failed; local imagery preserved.")},
        {QStringLiteral("已加载天地图卫星影像。"), QStringLiteral("Tianditu satellite imagery loaded.")},
        {QStringLiteral("部分影像缺失：周边区域统一使用同源较低级别影像；仍无数据处显示灰色。"), QStringLiteral("Some imagery is missing. Nearby areas use lower detail from the same source; unavailable areas appear gray.")},
        {QStringLiteral("放大到近景，正在自动加载 Sentinel-2 本地影像..."), QStringLiteral("Close view: automatically loading local Sentinel-2 imagery...")},
        {QStringLiteral("已自动加载 Sentinel-2 本地影像，已保留当前视角。"), QStringLiteral("Local Sentinel-2 imagery loaded automatically; view preserved.")},
        {QStringLiteral("自动加载 Sentinel-2 本地影像失败: %1"), QStringLiteral("Automatic Sentinel-2 imagery load failed: %1")},
        {QStringLiteral("自动加载 Earth 文件失败，已保留当前场景: %1"), QStringLiteral("Automatic Earth file load failed; scene preserved: %1")},
        {QStringLiteral("自动加载 Earth 文件失败，已保留当前场景。"), QStringLiteral("Automatic Earth file load failed; scene preserved.")},
        {QStringLiteral("自定义 Earth 失败，正在加载自动地图: %1"), QStringLiteral("Custom Earth failed; loading automatic map: %1")},
        {QStringLiteral("%1：已设为显示，当前场景加载该数据后自动生效"), QStringLiteral("%1: enabled; will appear when its data is loaded")},
        {QStringLiteral("请先点击“启动渲染”，再加载 Earth 文件。"), QStringLiteral("Start rendering before loading an Earth file.")},
        {QStringLiteral("请先点击“启动渲染”，再加载本地影像。"), QStringLiteral("Start rendering before loading local imagery.")},
        {QStringLiteral("请先点击“启动渲染”，再加载本地 3D 建筑。"), QStringLiteral("Start rendering before loading local 3D buildings.")},
        {QStringLiteral("请先点击“启动渲染”，再加载飞机模型。"), QStringLiteral("Start rendering before loading an aircraft model.")},
        {QStringLiteral("请先点击“启动渲染”，再重载最佳本地地图。"), QStringLiteral("Start rendering before reloading the best local map.")},
        {QStringLiteral("[界面测试] 地图偏好已沙箱化，网络地图和资源写入已禁用。"), QStringLiteral("[UI test] Map preferences are isolated; network maps and resource writes are disabled.")},
        {QStringLiteral("[界面测试] 地图网络加载已禁用；仍可显示模拟轨迹。"), QStringLiteral("[UI test] Network map loading is disabled; simulated tracks remain available.")},
        {QStringLiteral("[界面测试] 天地图网络图层已禁用。"), QStringLiteral("[UI test] Tianditu network layers are disabled.")},
        {QStringLiteral("[界面测试] 已模拟 Earth 文件加载；未访问外部资源。"), QStringLiteral("[UI test] Earth file loading simulated; no external resources accessed.")},
        {QStringLiteral("[界面测试] 已模拟会话目录选择；未读取业务文件。"), QStringLiteral("[UI test] Session folder selection simulated; no user files read.")},
        {QStringLiteral("[界面测试] 已模拟会话轨迹加载；未读取业务文件。"), QStringLiteral("[UI test] Session track loading simulated; no user files read.")},
        {QStringLiteral("[界面测试] 已模拟地图重载；未访问外部资源。"), QStringLiteral("[UI test] Map reload simulated; no external resources accessed.")},
        {QStringLiteral("[界面测试] 已模拟影像模板加载；未访问外部资源。"), QStringLiteral("[UI test] Imagery template loading simulated; no external resources accessed.")},
        {QStringLiteral("[界面测试] 已模拟本地 3D 建筑加载；未读取外部资源。"), QStringLiteral("[UI test] Local 3D building loading simulated; no external resources read.")},
        {QStringLiteral("[界面测试] 已模拟飞机模型选择；未读取外部文件。"), QStringLiteral("[UI test] Aircraft model selection simulated; no external files read.")},
        {QStringLiteral("RTK 固定解"), QStringLiteral("RTK fixed")},
        {QStringLiteral("RTK 浮点解"), QStringLiteral("RTK float")},
        {QStringLiteral("差分定位"), QStringLiteral("Differential fix")},
        {QStringLiteral("无效定位"), QStringLiteral("Invalid fix")},
        {QStringLiteral("定位质量未知"), QStringLiteral("Unknown fix quality")},
        {QStringLiteral("平均海平面"), QStringLiteral("Mean sea level")},
        {QStringLiteral("局部 NED"), QStringLiteral("Local NED")},
        {QStringLiteral("高程基准未知"), QStringLiteral("Unknown height reference")},
        {QStringLiteral("轨迹点详细信息"), QStringLiteral("Track sample details")},
        {QStringLiteral("轨迹点 #%1"), QStringLiteral("Track sample #%1")},
        {QStringLiteral("卫星 %1 · HDOP %2 · VDOP %3"), QStringLiteral("Satellites %1 - HDOP %2 - VDOP %3")},
        {QStringLiteral("横滚 %1° · 俯仰 %2° · 航向 %3°"), QStringLiteral("Roll %1° - Pitch %2° - Heading %3°")},
        {QStringLiteral("记录时间"), QStringLiteral("Record time")},
        {QStringLiteral("经纬度"), QStringLiteral("Latitude / longitude")},
        {QStringLiteral("高程"), QStringLiteral("Height")},
        {QStringLiteral("定位精度"), QStringLiteral("Position accuracy")},
        {QStringLiteral("三维速度"), QStringLiteral("3D speed")},
        {QStringLiteral("姿态"), QStringLiteral("Attitude")},
        {QStringLiteral("无法创建 OpenGL 渲染上下文，请检查显卡驱动"), QStringLiteral("Unable to create OpenGL context; check the graphics driver")},
        {QStringLiteral("渲染运行库初始化失败"), QStringLiteral("Rendering runtime initialization failed")},
        {QStringLiteral("OpenGL 上下文不可用"), QStringLiteral("OpenGL context unavailable")},
        {QStringLiteral("OpenGL 初始化失败"), QStringLiteral("OpenGL initialization failed")},
        {QStringLiteral("渲染视口调整失败"), QStringLiteral("Render viewport resize failed")},
        {QStringLiteral("渲染帧失败"), QStringLiteral("Frame rendering failed")},
    };
    return catalog;
}
inline QString mapText(const QString& text) {
    return QCoreApplication::instance() && QCoreApplication::instance()->property("vaporViewEnglish").toBool()
        ? mapLanguageCatalog().value(text, text) : text;
}
// Convert complete messages; never translate arbitrary substrings of paths or IDs.
inline QString mapRenderedText(const QString& text, bool english)
{
    if (text.isEmpty()) return text;
    const auto& catalog = mapLanguageCatalog();
    if (english && catalog.contains(text)) return catalog.value(text);
    if (!english) {
        for (auto it = catalog.cbegin(); it != catalog.cend(); ++it)
            if (it.value() == text) return it.key();
    }
    struct MessageRule {
        QRegularExpression expression;
        QString chinese;
        QString english;
        QStringList placeholders;
        int specificity = 0;
    };
    static const QList<MessageRule> rules = [] {
        QList<MessageRule> result;
        const QRegularExpression tokenExpression(QStringLiteral("%[1-9][0-9]*"));
        for (auto it = mapLanguageCatalog().cbegin(); it != mapLanguageCatalog().cend(); ++it) {
            for (const QString& source : {it.key(), it.value()}) {
                if (!source.contains(tokenExpression) || source == QStringLiteral("%1")) continue;
                MessageRule rule;
                rule.chinese = it.key();
                rule.english = it.value();
                QString pattern;
                int previous = 0;
                auto tokens = tokenExpression.globalMatch(source);
                while (tokens.hasNext()) {
                    const auto token = tokens.next();
                    const QString literal = source.mid(previous, token.capturedStart() - previous);
                    pattern += QRegularExpression::escape(literal) + QStringLiteral("(.*?)");
                    rule.specificity += literal.size();
                    rule.placeholders.append(token.captured());
                    previous = token.capturedEnd();
                }
                pattern += QRegularExpression::escape(source.mid(previous));
                rule.specificity += source.size() - previous;
                rule.expression = QRegularExpression(QStringLiteral("\\A") + pattern + QStringLiteral("\\z"),
                    QRegularExpression::DotMatchesEverythingOption);
                result.append(rule);
            }
        }
        std::stable_sort(result.begin(), result.end(), [](const MessageRule& a, const MessageRule& b) {
            return a.specificity > b.specificity;
        });
        return result;
    }();
    for (const auto& rule : rules) {
        const auto match = rule.expression.match(text);
        if (!match.hasMatch()) continue;
        const QString output = english ? rule.english : rule.chinese;
        QString translated;
        int previous = 0;
        auto tokens = QRegularExpression(QStringLiteral("%[1-9][0-9]*")).globalMatch(output);
        while (tokens.hasNext()) {
            const auto token = tokens.next();
            translated += output.mid(previous, token.capturedStart() - previous);
            const int index = rule.placeholders.indexOf(token.captured());
            const QString value = index >= 0 ? match.captured(index + 1) : token.captured();
            translated += value == text ? value : mapRenderedText(value, english);
            previous = token.capturedEnd();
        }
        return translated + output.mid(previous);
    }
    return text;
}
}
