#pragma once

#include "ground/main/MainWindow.h"
#include "ground/main/GroundMainWindowState.h"
#include "shared/config/SettingsWriteBarrier.h"
#include "shared/theme/AppTheme.h"
#include "shared/theme/TopLevelCardStyle.h"
#include "ground/widgets/CustomTitleBar.h"
#ifdef VAPORVIEW_HAS_OSGEARTH
#include "ground/map/Map3DController.h"
#endif
#include "ground/main/GroundMainWindowSupport.h"
#include "ground/devices/RemoteTelemetryDecoder.h"
#include "ground/devices/UiTestDataModel.h"
#include "ground/devices/EpsilonConfigurationService.h"
#include "ground/devices/ImuConfigurationService.h"
#include "ground/devices/DeviceRatePolicy.h"
#include "ground/devices/LocalDeviceConnectionController.h"
#include "ground/devices/RemoteSkyController.h"
#include "ground/devices/SerialPortDetectionService.h"
#include "ground/devices/TemperatureCommandState.h"
#include "ground/session/GroundRecordingService.h"
#include "ground/session/RecordingScheduleController.h"
#include "ground/session/RecordingSessionLayout.h"
#include "ground/widgets/EpsilonPanel.h"
#include "ground/widgets/DevicePanelCoordinator.h"
#include "ground/widgets/TelemetryPanels.h"
#include "ground/widgets/TemperatureControllerWidgets.h"
#include "ground/rtk/RtkConfigDialog.h"
#include "ground/session/SessionViewerWindow.h"
#include "ground/widgets/SkyDeviceConfigDialog.h"
#include "shared/theme/SingleLevelPopupMenu.h"
#include "TcpWaveEncoding.h"
#include "ground/wave/TcpWavePanel.h"
#include "ground/widgets/VisualTextLabel.h"
#include "ground/widgets/WindowSizing.h"
#include "data_collector.h"
#include "data_types.h"
#include <QMenu>
#include <QAbstractItemView>
#include <QAbstractButton>
#include <QAbstractSpinBox>
#include <QAction>
#include <QButtonGroup>
#include <QCheckBox>
#include <QCloseEvent>
#include <QCursor>
#include <QDateTimeEdit>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDoubleValidator>
#include <QEvent>
#include <QFormLayout>
#include <QMessageBox>
#include <QMouseEvent>
#include <QFile>
#include <QFileInfo>
#include <QFileDialog>
#include <QFont>
#include <QFontDatabase>
#include <QFontMetrics>
#include <QSaveFile>
#include <QTextStream>
#include <QStringConverter>
#include <QDateTime>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QKeyEvent>
#include <QTimeZone>
#include <QGridLayout>
#include <QFrame>
#include <QScrollArea>
#include <QSplitter>
#include <QTimer>
#include <QDir>
#include <QDirIterator>
#include <QScrollBar>
#include <QShortcut>
#include <QScreen>
#include <QSpacerItem>
#include <QStringList>
#include <QApplication>
#include <QGuiApplication>
#include <QHelpEvent>
#include <QHoverEvent>
#include <QLayout>
#include <QIntValidator>
#include <QRegularExpression>
#include <QResizeEvent>
#include <QHash>
#include <QIcon>
#include <QImage>
#include <QPainter>
#include <QPainterPath>
#include <QPalette>
#include <QPaintEvent>
#include <QPolygonF>
#include <QPixmap>
#include <QRadioButton>
#include <QRegion>
#include <QSvgRenderer>
#include <QSet>
#include <QSignalBlocker>
#include <QSettings>
#include <QStackedWidget>
#include <QStandardItemModel>
#include <QStyle>
#include <QTabWidget>
#include <QStyleOptionButton>
#include <QStyleOptionSpinBox>
#include <QStyleOptionToolButton>
#include <QTextDocument>
#include <QThread>
#include <QToolButton>
#include <QToolTip>
#include <QTransform>
#include <QVariant>
#include <QVariantAnimation>
#include <QVector>
#include <QWidgetAction>
#include <QWindow>
#include <QtEndian>
#ifdef Q_OS_WIN
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <dwmapi.h>
#include <windows.h>
#include <windowsx.h>
#endif
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <functional>
#include <initializer_list>
#include <limits>
#include <map>
#include <memory>
#include <utility>
#include <vector>

using VaporView::AppThemeColor;
using VaporView::appThemeColor;
using VaporView::appThemeColorName;
using VaporView::appThemePalette;
using VaporView::appThemeRgba;
using VaporView::applyAppThemeTokens;
using VaporView::configureComboBoxPopup;
using VaporView::configureTopLevelCard;
using VaporView::kAppDarkThemeProperty;
using VaporView::updateTopLevelCardShadows;
using VaporView::SingleLevelPopupAnchor;
using VaporView::SingleLevelPopupMenu;
using VaporView::SingleLevelPopupMenuRow;
using VaporView::SingleLevelPopupTextAlignment;
using VaporView::Ground::Widgets::EpsilonPanel;
using VaporView::Ground::Widgets::DevicePanelBindings;
using VaporView::Ground::Widgets::DevicePanelCoordinator;
using VaporView::Ground::Widgets::DevicePanelRates;
using VaporView::Ground::Widgets::createSingleLevelPopupComboBox;
using VaporView::Ground::Widgets::createSourceModeOverviewSwitchButton;
using VaporView::Ground::Widgets::createTemperatureControllerOverviewPanel;
using CollectorSnapshot = VaporView::Ground::Devices::CollectorSet;
using VaporView::Ground::Devices::LocalSampleRateConfiguration;
using VaporView::Ground::Devices::LocalSampleRateApplyResult;
using VaporView::Ground::Devices::LocalTemperatureCommandStatus;
using RecordingScheduleController = VaporView::Ground::Session::RecordingScheduleController;
using MainWindowState = VaporView::Ground::Main::MainWindowState;
using namespace VaporView::Ground::DeviceRates;
using namespace VaporView::Ground::MainSupport;
